---
title: "Developing data products week4 Assignment"
author: "Tumelo Moabelo"
date: "04.05.2021"
output:
  slidy_presentation: default
  html_document:
    number_sections: yes
    toc: yes
  ioslides_presentation: default
mode: selfcontained
job: Reproducible Pitch Presentation
subtitle: Reproducible Pitch Presentation
highlighter: highlight.js
widgets: bootstrap
---


## Overview

The first part of this project, I have developed shiny app and deployed it on shiny server. The app shows the relationship between variables and miles per galon (MPG). We also try to find out whether automatic or manual Transmision vehicle has better MPG. The code can be found at URL: https://github.com/Moabelo-TS/Developing-Data-products-Week4-Assignment.git


---

## mtcars Dataset


> These data was obtained from the 1974 Motor Trend US magazine, and comprises fuel consumption and 10 aspects of automobile design and performance for 32 automobiles (1973-74 models).
```{r}
library(datasets)
head(mtcars, 5)
```

---

## mtcars Dataset - Format

### 11 Variables within data frame with 32 observation

| Index | Field | Detail |
------- | ----- | ------ |
| [, 1] | mpg | Miles/(US) gallon |
| [, 2]  | cyl | Number of cylinders |
| [, 3]	| disp | Displacement (cu.in.) |
| [, 4]	| hp | Gross horsepower |
| [, 5]	| drat | Rear axle ratio |
| [, 6]	| wt | Weight (lb/1000) |
| [, 7]	| qsec | 1/4 mile time |
| [, 8]	| vs | V/S |
| [, 9]	| am | Transmission (0 = automatic, 1 = manual) |
| [,10]	| gear | Number of forward gears |
| [,11]	| carb | Number of carburetors |

---

## Code

```r
  formulaTextPoint <- reactive({
    paste("mpg ~", "as.integer(", input$variable, ")")  })
  
  fit <- reactive({
    lm(as.formula(formulaTextPoint()), data=MilesPerGalon_Data)  })
  ...
  output$fit <- renderPrint({
    summary(fit()) })
  
  output$mpgPlot <- renderPlot({
    with(MilesPerGalon_Data, {
      plot(as.formula(formulaTextPoint()))
      abline(fit(), col=2)
    })  })
```